### ISSUE TITLE
MySQL passwordless accounts cannot be used

### ISSUE THREAD

**Issue by MickaelBergem** [aerofs/baseline#1]
In `MySQLHelper.java` (and possibly elsewhere), no checks are made on the MySQL password: an empty password will place the `-p` flag without argument, which will trigger a CLI prompt (asking for the password).

See for example ```String.format("%s/mysql -u%s -h%s -p%s -e 'create database if not exists %s default character set utf8mb4 collate utf8mb4_bin'", mysqlPath, mysqlUser, mysqlHost, mysqlPass, mysqlDatabase);```

The solution is to not include the `-p` flag if the password is blank.

**Comment by rudydai** [comment]
addressed in https://github.com/aerofs/baseline/commit/4dc4fed9b0c8c4b944ff3002e3c70df6c1c0275b
